In [1]:
print("hello world")

hello world


In [2]:
print("hi")

hi


In [3]:
import numpy as np

In [4]:
mylist = [1,2,3]

In [5]:
type(mylist)

list

In [6]:
np.array(mylist)

array([1, 2, 3])

In [7]:
import numpy as np

In [8]:
myarray = np.array(mylist)

In [9]:
 myarray

array([1, 2, 3])

In [10]:
type(myarray)

numpy.ndarray

In [11]:
np.arange(0,10,5
         )

array([0, 5])

In [12]:
np.zeros(shape=(10,5)) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(shape=(2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.random.seed(101)

In [16]:
import numpy as np

In [17]:
np.random.seed(191)
arr=np.random.randint(0,100,10)

In [18]:
arr

array([49,  3, 70, 69,  1, 91, 68, 14, 52, 24])

In [19]:
arr

array([49,  3, 70, 69,  1, 91, 68, 14, 52, 24])

In [20]:
arr

array([49,  3, 70, 69,  1, 91, 68, 14, 52, 24])

In [21]:
np.random.seed(101)

In [22]:
arr = np.random.randint(0,100,10)

In [23]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [24]:
arr2 = np.random.randint(0,100,10)

In [25]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [26]:
 arr.max()

95

In [27]:
arr.argmax()

0

In [28]:
arr.min()

9

In [29]:
arr.argmin()

7

In [30]:
arr.mean()

60.8

In [31]:
arr.shape

(10,)

In [32]:
arr.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [33]:
mat = np.arange(0,100).reshape(10,10)

In [34]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [35]:
mat.shape

(10, 10)

In [36]:
row = 0
col = 1

In [37]:
mat[row,col]

1

row = 6
col = 4

In [38]:
row = 4
col = 6

In [39]:
mat[row,col]

46

In [40]:
mat[4,6]

46

In [41]:
mat[row1 := 4, col1 := 6]

46

In [42]:
mat[1,:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [43]:
mat[2,:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [44]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [45]:
mat[2,1:3]

array([21, 22])

In [46]:
mat[0:6 , :] = 8569

In [47]:
mat

array([[8569, 8569, 8569, 8569, 8569, 8569, 8569, 8569, 8569, 8569],
       [8569, 8569, 8569, 8569, 8569, 8569, 8569, 8569, 8569, 8569],
       [8569, 8569, 8569, 8569, 8569, 8569, 8569, 8569, 8569, 8569],
       [8569, 8569, 8569, 8569, 8569, 8569, 8569, 8569, 8569, 8569],
       [8569, 8569, 8569, 8569, 8569, 8569, 8569, 8569, 8569, 8569],
       [8569, 8569, 8569, 8569, 8569, 8569, 8569, 8569, 8569, 8569],
       [  60,   61,   62,   63,   64,   65,   66,   67,   68,   69],
       [  70,   71,   72,   73,   74,   75,   76,   77,   78,   79],
       [  80,   81,   82,   83,   84,   85,   86,   87,   88,   89],
       [  90,   91,   92,   93,   94,   95,   96,   97,   98,   99]])